# Generated by Django 4.0.4 on 2022-06-19 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=150)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('pan_card_number', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('EC', 'EC'), ('Civil', 'Civil'), ('NTD', 'NTD'), ('MECH', 'MECH'), ('MATHS', 'MATHS'), ('PHYSICS', 'PHYSICS'), ('CHEMISTRY', 'CHEMISTRY'), ('LIBRARY', 'LIBRARY')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=20)),
                ('shared_amount', models.IntegerField(default=0)),
                ('loan_balance', models.IntegerField(choices=[(100000, 100000), (50000, 50000), (0, 0)])),
                ('loan_left', models.IntegerField(default=0)),
                ('savings', models.IntegerField(default=0)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsavings', models.IntegerField()),
                ('loan_left', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.lecturers')),
            ],
        ),
    ]
