# Generated by Django 4.0.4 on 2022-06-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturers',
            old_name='savings',
            new_name='emi',
        ),
    ]
