# Generated by Django 4.0.4 on 2022-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_savings_lecturers_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturers',
            name='savings',
            field=models.IntegerField(default=0),
        ),
    ]
