# Generated by Django 4.0.4 on 2022-06-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_lecturers_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='hsavings',
            new_name='hemi',
        ),
    ]
